[package]
name = "tripa"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
http-body-util = "0.1.2"
mime = "0.3.17"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
tower = "0.4.13"
tracing-subscriber = "0.3.18"
